### ISSUE TITLE
max time allowed

### ISSUE THREAD

**Issue by ivar** [matthewjamesadam/epyc#3]
It would be cool if you could define a maximum wait time for a person to do their turn. The next player in line would then be assigned the turn. The player who missed their turn could be removed from the game or moved to the end of the turn queue.

**Comment by matthewjamesadam** [comment]
I've added a 'leave' command -- I think maybe the following makes sense:

* Send a warning DM daily to the current player
* After some period (2 days?) drop them from the game
* Add a link on the play UI to skip your turn (easier then using the bot commands)
