### ISSUE TITLE
Inconsistency when explicitly specifying players in addition to 'available' for new game

### ISSUE THREAD

**Issue by ivar** [matthewjamesadam/epyc#86]
Below are the logs for trying to create a new game with both the pool of 'available' players, plus one specific user explicitly. The initial command looks good, but the game info in the response from the `status` command does not include the specified player. When the player tries to `join` the game, Epyc replies that they are already part of the game. 
--- 

**Spiph — Today at 9:45 AM**
@Epyc start @iJi [ee-gh-ee] available

**EpycBOT — Today at 9:45 AM**
Game sagenjete has begun!  It is now Neudel's turn.

**Spiph — Today at 9:45 AM**
@Epyc status

**EpycBOT — Today at 9:45 AM**
 The following games are in progress:
• sagenjete: Waiting on Neudel.  0 turns completed, 6 remaining.

 The following people are available to play in this channel: djjj, rockpooling, Neudel, Markus huffnpuff, Wren_Hieu
 To see previous games for this channel click here: https://epyc.phlegmatic.ca/games/discord/831614520619040818

**Spiph — Today at 9:46 AM**
hmm. no iJi - I guess they'll have to add themselves 

**iJi [ee-gh-ee] — Today at 9:56 AM**
@Epyc join sagenjete

**EpycBOT — Today at 9:56 AM**
You are already in game sagenjete

**Comment by matthewjamesadam** [comment]
@ivar maybe I'm misunderstanding (or, possibly, the command output is confusing), but I don't think I see the bug in this output?

You started the game with people in the channel, plus @iji.  When you later issued the status command, it reported this:

```
The following people are available to play in this channel: djjj, rockpooling, Neudel, Markus huffnpuff, Wren_Hieu
```

These aren't the people in the game, they're the people available to play in the channel (through `@epyc start available`).  I don't think there's a command that gives the people in the game right now...

**Comment by iji** [comment]
Not “iji”, but “iji [ee-gh-ee]“. Different person here 😂

**Comment by matthewjamesadam** [comment]
Ah sorry for the disturbance @iji  -- different handle in a totally different (non-github) context, I didn't mean to bring you into this!

@ivar Ijust took a look at the database and `iJi [ee-gh-ee]` is indeed in the game, in the third frame.  They have played their turn.  I think this is working as expected, but please do re-open if you disagree...
